# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - FCV3DConfigurator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Increase file descriptor limit
        run: ulimit -n 4096
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install, build, and test
        run: |
          npm ci
          NODE_OPTIONS="--max-old-space-size=4096" npm run build --if-present
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: Set up environment variables
        run: |
          echo "AUTODESK_CLIENT_ID=${{ secrets.AUTODESK_CLIENT_ID }}" >> ./build/standalone/.env
          echo "AUTODESK_CLIENT_SECRET=${{ secrets.AUTODESK_CLIENT_SECRET }}" >> ./build/standalone/.env

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0AC9D2F893EB465CB9D30531076058C6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3BC02B276ECC4A1193C8998D6331680E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_148AB3FC4E544DD095F0A6DC084923E5 }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./build/standalone
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FCV3DConfigurator'
          package: ./build/standalone

